name: Deploy External Next.js App

on:
  workflow_dispatch:  # запуск вручную

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment repo (для push)
        uses: actions/checkout@v3

      - name: Checkout source Next.js repo
        uses: actions/checkout@v3
        with:
          repository: VisionVello/VisionWeb
          path: app
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Build Next.js app
        run: |
          cd app
          npx next build

      - name: Export static site
        run: |
          cd app
          npx next export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: VisionVello/deploy
          publish_branch: gh-pages
          publish_dir: ./app/out
