name: Deploy External React App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v3

      - name: Checkout source React repo
        uses: actions/checkout@v3
        with:
          repository: VisionVello/VisionWeb
          path: app
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Build React App
        run: |
          cd app
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./app/build
          external_repository: VisionVello/deploy
          publish_branch: gh-pages

